name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [1.8, 11]
    runs-on: ${{ matrix.os }}
    name: Check JDK ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - name: git clone
      uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: "./gradlew check"
      uses: eskatos/gradle-command-action@v1
      with:
          arguments: check
    - name: "Comment build scan url"
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request' && failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ ${{ github.workflow }} ${{ matrix.java }} on ${{ matrix.os }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
          })
